
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";

const CampaignBuilder = lazy(() => import("./pages/CampaignBuilder.tsx"));

export const userRoutes: RouteObject[] = [
	{ path: "/", element: <CampaignBuilder />},
	{ path: "/campaign-builder", element: <CampaignBuilder />},
];
